# Generated by Django 5.1.3 on 2024-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.FileField(upload_to='posts/')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_time'],
            },
        ),
    ]
