# Generated by Django 5.1.3 on 2024-11-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.URLField(),
        ),
    ]
