# Generated by Django 5.1.3 on 2024-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('like', 'Like')], max_length=50)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_time'],
            },
        ),
    ]
